### ISSUE TITLE
About string parameters

### ISSUE THREAD

**Issue by Zylann** [godot-zig/godot-zig#20]
I noticed every function that normally takes a `String` or `StringName` takes `[]const u8` instead.

It's relatively minor, but I'm not sure if that's a good idea. It hides the real API, complexifies the bindings and causes more conversions than necessary in cases where the caller already has a `String` or `StringName`. In particular with `StringName`, where constructing a new one everytime is more expensive than a `String`.
This is one of the things among others that made me consider making my own bindings, but I would prefer using yours if possible.

Side note: in the generated bindings, `Object.call` creates a `String` instead of a `StringName` to pass the `method` argument, which is yet another conversion Godot will have to do. Other methods might have the same issue.

**Comment by elvisxzhou** [comment]
I implemented the api initially as you described, but it turned out to be cumbersome to use, for performance sake a comptime check againt the type can improve it, I have no strong opinion on which way should go.
As this is a thin wrapper, I dont think it's worthy to write another one in Zig, welcome to join godot-zig and improve it to satisfy all.

**Comment by elvisxzhou** [comment]
String, StringName or []const u8 are all valid after 6aef5de0ece32f5b6e7a6f055a2ad38da268cd9d
